resource_group_name       = "lbsusecase-rg"
location                  = "Canada Central"
function_app_name         = "lbsusecasefa"
sql_server_name           = "lbsusecaseSQLServer"
sql_database_name         = "lbsusecaseDatabase"
sql_admin_username        = "sqladmin"
sql_admin_password        = "P@ssw0rd1234!"
